spring.application.name=demo
spring.datasource.url = jdbc:h2:mem:demo
spring.h2.console.enabled=true
spring.sql.init.mode=always
spring.sql.init.encoding=utf-8
spring.jpa.hibernate.ddl-auto=none
spring.h2.console.path=/h2-console

spring.profiles.active=dev

spring.ai.openai.api-key=${OPENAI_API_KEY}

spring.ai.vectorstore.qdrant.host=localhost
spring.ai.vectorstore.qdrant.port=6334
spring.ai.vectorstore.qdrant.collection-name=pdf-docs
spring.ai.vectorstore.qdrant.initialize-schema=true